### ISSUE TITLE
Join videos?

### ISSUE THREAD

**Issue by believer-ufa** [CineEncoder/cine-encoder#15]
Hello and thank you for this beautiful piece of software! HDR support currently is really lacks in most video editors, and this software was like a jewel when i found about it.

Can you please look at ability to join all videos in task queue into one final video file?

**Comment by CineEncoder** [comment]
Hi!
OK, I'll try to make this possible in version 3.5.

**Comment by believer-ufa** [comment]
I just found that it [can be done](https://stackoverflow.com/questions/7333232/how-to-concatenate-two-mp4-files-using-ffmpeg) with commands to ffmpeg. Maybe its not so important - to add this function into Cine Encoder :) That's why i've closed it earlier.

**Comment by CineEncoder** [comment]
I thought that I had accidentally closed it.
Yes, it is also possible directly via FFmpeg, but I will also add this feature to the Cine Encoder.
