### ISSUE TITLE
Q_OS_LINUX -> Q_OS_UNIX

### ISSUE THREAD

**Issue by danfe** [CineEncoder/cine-encoder#20]
The program should not assume that any non-Windows, Unix-like system is GNU/Linux, yet currently, in version 3.4, there are three `#ifdef Q_OS_LINUX` in `app/mainwindow.cpp` and `app/settings.cpp` files.  Consider using more appropriate `Q_OS_UNIX` macro instead.

**Comment by CineEncoder** [comment]
Hi! The idea was to exclude the possibility of compilation if the system does not belong to either Windows or Linux, since I do not yet know how this will work with other Unix systems other than Linux.

**Comment by danfe** [comment]
It builds and works just fine on e.g. FreeBSD.  As it is essentially being a nice graphical frontend to FFmpeg and MKVtoolnix, I don't see why would you want to artificially limit it to GNU/Linux.

**Comment by CineEncoder** [comment]
If it works at least for FreeBSD, I will make this replacement.

**Comment by CineEncoder** [comment]
Hi! I made this replacement in the master branch.

**Comment by danfe** [comment]
Thanks!  Fixed in a8884b4, closing.
