### ISSUE TITLE
Looks strange for default setting

### ISSUE THREAD

**Issue by denisoster** [CineEncoder/cine-encoder#5]
Looks strange for default setting 🤷

![2020-11-06-162404_3840x2160_scrot](https://user-images.githubusercontent.com/15886355/98376692-c2e6d880-203b-11eb-9071-1e61d37e75cb.png)

**Comment by CineEncoder** [comment]
This bug was detected in some desktop environments . I'll take it for correction.

**Comment by CineEncoder** [comment]
Today I updated the release of the program, removed some bugs.

**Comment by denisoster** [comment]
1. Problem persists.
2. Please remove the hard depends to [ffmpeg](https://www.archlinux.org/packages/extra/x86_64/ffmpeg/). Add choice [ffmpeg](https://www.archlinux.org/packages/extra/x86_64/ffmpeg/) or [ffmpeg-full] (https://aur.archlinux.org/packages/ffmpeg-full/) during installation.
3. It would be nice if the program does it automatically 

> Make sure that the NVIDIA drivers are installed in accordance with the following requirements: Using FFMPEG with NVIDIA.

**Comment by CineEncoder** [comment]
1.Probably the problem remained because the cache was not cleared. Try clearing the cache for AUR and reinstall the program. The white background should disappear.
 
2.I will need to think about how to do this, since I still have the .rpm and .deb packages.

**Comment by denisoster** [comment]
I`m installed without cache

**Comment by CineEncoder** [comment]
Is the white background still there?

**Comment by denisoster** [comment]
Yes white background present

**Comment by CineEncoder** [comment]
This is very strange...
Can you tell me how you install the package?
Is this exactly the latest version?
Install latest version from: https://github.com/CineEncoder/cine-encoder/releases
or from AUR.
In the new version, this simply can't happen, because I explicitly specified the background and font colors on the buttons and also checked in different graphic environments, there is no white background anywhere.

**Comment by CineEncoder** [comment]
I made adjustments again, and it may work now.

**Comment by denisoster** [comment]
![2020-11-11-234926_3840x2160_scrot](https://user-images.githubusercontent.com/15886355/98868694-700c8700-2468-11eb-86d6-d72ca1010f11.png)
looks more usable

**Comment by CineEncoder** [comment]
I will need to fix the placement of text on the panels, I see that it does not fit .
