### ISSUE TITLE
.deb package depends on libmediainfo-dev

### ISSUE THREAD

**Issue by Lastique** [CineEncoder/cine-encoder#7]
Debian/Ubuntu package cine-encoder-3.1_amd64.deb has a dependency on libmediainfo-dev. -dev packages should be build dependencies, but not runtime dependencies.

**Comment by CineEncoder** [comment]
Thanks!
Replaced this with libmediainfo0v5: https://github.com/CineEncoder/cine-encoder/blob/master/distros/debian/control

**Comment by Lastique** [comment]
You should not have to specify the package, it should be added via the `shlibs:Depends` replacement.

**Comment by CineEncoder** [comment]
This time I think I did everything right: https://github.com/CineEncoder/cine-encoder/blob/master/distros/debian/control
